# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Takeo Kunishima/国島丈生
email: t.kunishi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 70% a software meister, 30% an educator
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kunishi.github.io" # the base hostname & protocol for your site
timezone: Asia/Tokyo
twitter_username: kunishi
github_username:  kunishi

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "vendor", "script"]
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
